name: document_saver_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-276.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  file_picker: ^5.3.2
  open_file: ^3.3.2
  dotted_border: ^2.0.0+3
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.4
  intl: ^0.18.1
  syncfusion_flutter_pdfviewer: ^22.1.34
  http: ^1.1.0
  path_provider: ^2.0.15
  flutter_image: ^4.1.6
  flutter_html: ^3.0.0-beta.2
  flutter_pdfview: ^1.3.1
  webview_flutter: ^4.2.2
  photo_view: ^0.14.0
  flutter_conditional_rendering: ^2.0.0
  universal_html: ^2.2.3
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.2
path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/document.png
    - lib/assets/register.png
    - lib/assets/confusion.png
    - lib/assets/pdf_type.png
    - lib/assets/image_type.png
    - lib/assets/upload.png
    - lib/assets/generic_file.png
    - lib/assets/empty.png
