// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDLhfzZAtHiSXtu-q2phfKb-sycpUZ_d0',
    appId: '1:832568582582:web:33540c3d2e1a4c0a0f6117',
    messagingSenderId: '832568582582',
    projectId: 'newfile-92a2c',
    authDomain: 'newfile-92a2c.firebaseapp.com',
    databaseURL: 'https://newfile-92a2c-default-rtdb.firebaseio.com',
    storageBucket: 'newfile-92a2c.appspot.com',
    measurementId: 'G-VDC19DVBGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7r8GuI2BW4bay0QBxPoDirk3wq7BLIBg',
    appId: '1:832568582582:android:d1fd83b2551ad1040f6117',
    messagingSenderId: '832568582582',
    projectId: 'newfile-92a2c',
    databaseURL: 'https://newfile-92a2c-default-rtdb.firebaseio.com',
    storageBucket: 'newfile-92a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJA3rlHL8iWg5wN6n7WzlbdMZGs1nMjPw',
    appId: '1:832568582582:ios:7bc4119a0ca796370f6117',
    messagingSenderId: '832568582582',
    projectId: 'newfile-92a2c',
    databaseURL: 'https://newfile-92a2c-default-rtdb.firebaseio.com',
    storageBucket: 'newfile-92a2c.appspot.com',
    iosClientId: '832568582582-ur519bsfc41jv45metagg34om7f05ifc.apps.googleusercontent.com',
    iosBundleId: 'com.example.documentSaverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJA3rlHL8iWg5wN6n7WzlbdMZGs1nMjPw',
    appId: '1:832568582582:ios:6722f34d35c564f00f6117',
    messagingSenderId: '832568582582',
    projectId: 'newfile-92a2c',
    databaseURL: 'https://newfile-92a2c-default-rtdb.firebaseio.com',
    storageBucket: 'newfile-92a2c.appspot.com',
    iosClientId: '832568582582-2kv1hdefp4s7meq95cftib22gk21fp3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.documentSaverApp.RunnerTests',
  );
}
